# Generated by Django 4.2.9 on 2026-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('RESPONDER', 'Emergency Responder'), ('ADMIN', 'Administrator'), ('SUPERADMIN', 'Super Administrator')], default='PATIENT', max_length=20),
        ),
    ]
